name: Publish Docker image
on: [push]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: |
            anyakichi/myenv
            ghcr.io/anyakichi/myenv
          tags: latest
      - uses: docker/metadata-action@v3
        id: meta-slim
        with:
          images: |
            anyakichi/myenv
            ghcr.io/anyakichi/myenv
          tags: slim
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile.slim
          push: ${{ github.ref == 'refs/heads/main' }}
          build-args: |
            BUILD_USER=${{ secrets.BUILD_USER }}
            BUILD_GROUP=${{ secrets.BUILD_GROUP }}
            GIT_EMAIL=${{ secrets.GIT_EMAIL }}
            GIT_NAME=${{ secrets.GIT_NAME }}
          tags: ${{ steps.meta-slim.outputs.tags }}
          labels: ${{ steps.meta-slim.outputs.labels }}
      - uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
